### ISSUE TITLE
Unresolved reference: BuildConfig

### ISSUE THREAD

**Issue by eekboom** [bnorm/kotlin-ir-plugin-template#1]
Fresh checkout
`gradle build` results in 

```
kotlin-ir-plugin-template\kotlin-ir-plugin-native\src\main\kotlin\com\bnorm\template\TemplateCommandLineProcessor.kt: (36, 35): Unresolved reference: BuildConfig

FAILURE: Build failed with an exception.
```

**Comment by bnorm** [comment]
Are you using the included Gradle wrapper or a local installed version of Gradle? If local, what version? The project includes wrapper version 6.7.1, builds fine via GitHub Actions, and locally for me using the wrapper. I wonder if it's not the Gradle version, if it could be something environmental?

**Comment by eekboom** [comment]
Thanks for the answer!
It does indeed work from the command line.
It seems to be a bug in IntelliJ IDEA. The build fails if I have the option "Use Gradle from" set to "'gradle-wrapper.properties' file' and works fine if it is set to "'wrapper' task in Gradle build script". I don't think that should make a difference.
I filed https://youtrack.jetbrains.com/issue/IDEA-260181 for that.

**Comment by eekboom** [comment]
Just FYI: It is either a bug in gradle itself or in the buildconfig plugin.
At least I can reproduce it on the command line as described here. It seemed to be caused by me having enabled `org.gradle.parallel=true` (which I have enabled by default in ~/gradle.properties),
I filed https://github.com/gradle/gradle/issues/15938
